FROM debian:11.6

#hostname
ENV HOSTNAME dnsdemogitjava
  
# locale to german
ENV LANG=de_DE.ISO-8859-1
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.ISO-8859-1

ENV TZ Europe/Berlin

EXPOSE 53

  
# add h2 database to root folder
ADD https://github.com/demogitjava/demodatabase/raw/master/demodb.mv.db /root/demodb.mv.db

# get dns jar 
ADD https://github.com/demogitjava/demodatabase/raw/master/dockerdnsserver-1.0-SNAPSHOT.jar /root/dockerdnsserver-1.0-SNAPSHOT.jar

COPY root/dockerdnsserver-1.0-SNAPSHOT.jar dockerdnsserver-1.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "dockerdnsserver-1.0-SNAPSHOT.jar"]


